sudo: required
dist: trusty
language: python
python:
  - "2.7"
node_js:
  - "0.12"
env:
  global:
    - secure: Fd+dALSXhRgP44UaiED0xbJMHLxzON1Vcu6ufxDGgyl9NYepT0cfMGczLocfawc35ig++SyfytfpaPRhy3yG7WhNiBmpq+M1rec5MDKh/tFSKV/JOmLxbUIAxByIgTH39e+bY2El0h+vqiB12JiArahBzraYMYY+Xkty3Ysr+9o=
    - secure: clvOWlojaHQMHGhrN+sG+jOVLAsGJQFpzlUBv+8tKNy+Xbv/XPOQvnzqFTCdRlHSd39wnwIQTwOCWaCYhEECEyqgpaxYlYpSPsUOmk12aSxfjH5YGdwFqZvqhw1rkBpaEyoLh4PT0d1oLeCcJvb0jNuU4YbYOtq7DIRJDih/hPg=
  matrix:
    - GLTEST='unit'
    - GLTEST='build_and_install'
    - GLTEST='end2end-0' BROWSER='ie 10'
    - GLTEST='end2end-1' BROWSER='ie 11'
    - GLTEST='end2end-2' BROWSER='edge 20.10240'
    - GLTEST='end2end-3' BROWSER='firefox 34'
    - GLTEST='end2end-4' BROWSER='firefox 42'
    - GLTEST='end2end-5' BROWSER='chrome 37'
    - GLTEST='end2end-6' BROWSER='chrome 46'
    - GLTEST='end2end-7' BROWSER='safari 8'
    - GLTEST='end2end-8' BROWSER='safari 9'
    - GLTEST='end2end-9' BROWSER='android 4.4'
    - GLTEST='end2end-10' BROWSER='android 5.1'
    - GLTEST='end2end-11' BROWSER='iphone 7.1'
    - GLTEST='end2end-12' BROWSER='iphone 9.1'
addons:
  sauce_connect: true
install:
    - true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux && unzip chrome.zip
script:
  - $TRAVIS_BUILD_DIR/scripts/travis.sh
